### ISSUE TITLE
[Bug] AB3000 - Erroneous "Power" values

### ISSUE THREAD

**Issue by Youpimatin** [Zendure/Zendure-HA#690]
### Home Assistant Version

2025.7.3

### Zendure Integration Version

v1.1.3

### Describe the bug

BMS Firmware v1.0.7

Sometimes, aroud changes of sign for the battery current (at low powers), there are HIGH values for Power (around 2^16)

I think it's a BMS firmware little bug, with signed/unsigned values (maybe a problem caused by time lapse between 2 ADC reads while changing AC mode, or something else)

In my logs, I got values of :
65483 (65536-53), values of power just before and after are 5W and 58W
65487 (three times)
65484 (three times)
65483 (again)

Maybe it's possible to bring the problem to light up to Zendure, or to mask it by complementing values above 61500 ? (around 65536-4000 W)

### To Reproduce

Just check the logs

### Expected Behaviour

No value above 4kW ?

### What device are you using?

SF2400 AC

### Log Extracts

<img width="818" height="809" alt="Image" src="https://github.com/user-attachments/assets/6ab6a161-f305-4180-9e5f-f1f0ac8c09ed" />

**Comment by FireSon** [comment]
@Youpimatin Thanks for sharing this information! I checked my AB3000, and I do not have these strange values at all. Do you have the latest Firmware installed? 

The Integration only displays the information it gets from the device, so if this problem keeps happening, I think you should contact the Zendure servicedesk.

**Comment by Youpimatin** [comment]
I think I have the lastest firmware from Zendure :
- SolarFlow 2400 AC Firmware v1.0.6
- AB3000 BMS Firmware v1.0.7

**Comment by harrymayr** [comment]
Didn't we had a similar problem with one of the entities (signed int reported as unsinged int)?

**Comment by harrymayr** [comment]
So perhaps apply unsigned -> signed calculation not only for a factor of 10 (CONS_BATCUR), but for a factor >= 10 && <= 100 (factor for batVolt) in sensor.py? Maybe even in any case if the value > 32767

<img width="1114" height="274" alt="Image" src="https://github.com/user-attachments/assets/7c54f482-15e9-4ae7-b1da-11f091f0fcb1" />

**Comment by dav1dBoy** [comment]
Hi everyone, sorry for the late reply! 🙏

Battery Current (batcur) Data Conversion Description
The raw batcur data is stored as a 16-bit two’s complement value in a uint8_t[2] array.
During parsing, it should be converted into a signed 16-bit integer.
According to the protocol definition, divide the value by 10 to obtain the actual current, in amperes (A).

Please refer to Battery Properties
https://github.com/Zendure/zenSDK/blob/main/docs/en_properties.md

**Comment by FireSon** [comment]
Should be fixed in version 1.1.4-pre3

**Comment by Youpimatin** [comment]
@FireSon :

I uninstalled the integration,
installed from scratch version 1.1.4-pre7

I still have these high values : 65487 (four times in 24h)
