### ISSUE TITLE
[Bug] SF2400AC not switching to Discharge

### ISSUE THREAD

**Issue by CommanderROR9** [Zendure/Zendure-HA#964]
### Home Assistant Version

2025.12.4

### Zendure Integration Version

1.20

### Describe the bug

1.14 Pre-7 was running flawlessly for Months. Installed 1.20 and the SF2400AC did not switch to Discharge when the sun went down..I have it running via Zendure Manager "Manual" mode as always.

### To Reproduce

Wait for Sundown
Watch it keep pulling power from Grid instead of discharging

### Expected Behaviour

Switch to Discharge 

[latest-1.txt](https://github.com/user-attachments/files/24355449/latest-1.txt)

### What device are you using?

SF2400 AC

### Log Extracts

```shell

```

**Comment by harrymayr** [comment]
Can you add in device.py the following changes?

<img width="1202" height="225" alt="Image" src="https://github.com/user-attachments/assets/e4b27ca3-34fd-4d13-a674-2f394ca6685d" />

**Comment by CommanderROR9** [comment]
I just got back from work and don't feel up to doing that right now...sorry. i will just stay on Pre7 for now...and maybe try.your fixes when I have more free time. Sorry🤷‍♂️

**Comment by harrymayr** [comment]
Should be fixed with 1.2.1

**Comment by CommanderROR9** [comment]
> Should be fixed with 1.2.1

Yeah Thanks! Looks good so far,.but I will keep an eye on it for the next cycle or two to be sure🍀

**Comment by CommanderROR9** [comment]
![Image](https://github.com/user-attachments/assets/428e3f18-523d-4535-94c2-216adbe9ef55)

> Should be fixed with 1.2.1

I am very sorry, but it's not fixed.
It worked fine until my Automation kicked in for the nightly Charge. This should have set the manual power to -2400 in oder to charge the battery to full.
Unfortunately...the system completely ignored this and sid not charge at all. 
Back to pre-7 for me now since I have to be off to work.
I am not sure why this basic functionality is broken, since it requires no clever power balancing or anything...it should simply pass through the selected Value for Charge or Discharge, just like the older version does🤷‍♂️

**Comment by FireSon** [comment]
@CommanderROR9 do you have the corresponding logfile? The zendure manager power is updated, so I need to see the logging to investigate...

**Comment by CommanderROR9** [comment]
Sadly not this time. I was in a rush to get to work this morning, so all I could do was revert to pre-7 and then later add the Screenshot.
If I had to guess, then it's the usual problem. Zendure Manager is sending a positive value. 2400ac follows that value. Then the Manager sends a negative value and the 2400ac ignores it, because it expects to be told to switch from Discharge to Charge. 
Right now the SF2400AC is completely drained (because it didn't charge last night) so I can't really test anything right now.

**Comment by harrymayr** [comment]
@CommanderROR9 what is the refresh rate of your P1 sensor? And did you change TIMEFAST to a smaller value?

**Comment by CommanderROR9** [comment]
> [@CommanderROR9](https://github.com/CommanderROR9) what is the refresh rate of your P1 sensor?

I don't use a P1 Sensor. I have my own Automation(s) that write directly to the "Manual" part of the Zendure Manager. The value is updated every 30 Seconds since this seems a good compromise to balance my two Battery systems.

**Comment by harrymayr** [comment]
Hmm, this is strange, that it worked on 1.1.4-pre7. Because all the Manager action will be triggered on a state-change of the P1 sensor. Only input- and output-limit work directly.

**Comment by CommanderROR9** [comment]
> Hmm, this is strange, that it worked on 1.1.4-pre7. Because all the Manager action will be triggered on a state-change of the P1 sensor. Only input- and output-limit work directly.

I know it makes no sense. But pre-7 has been utterly reliable for 3 Months now and both 1.20 and 1.21 failed pretty much immediately.
My only (uneducated) guess is, that it is yet again somehow related to the fact that I have a few things permanently plugged into the OffGrid Socket. I guess nobody else is doing that🤷‍♂️

**Comment by harrymayr** [comment]
So there is really no sensor entered for the P1 in the configuration (at least now, the integration doesn't allow this)?
If there is some sensor which have some state change every 10 to ... seconds, than I can understand the behavior, even if the sensor don't provide any meaningful value. And then I have an idea to mitigate your issue.

**Comment by CommanderROR9** [comment]
> So there is really no sensor entered for the P1 in the configuration (at least now, the integration doesn't allow this)? If there is some sensor which have some state change every 10 to ... seconds, than I can understand the behavior, even if the sensor don't provide any meaningful value. And then I have an idea to mitigate your issue.

I added a Sensor (that Updates every 10 Seconds) when setting up the Integration. It just isn't used to actually control the Charging since I rely purely on the "Manual Mode" in Zendure Manager.

**Comment by CommanderROR9** [comment]
Quick addition:
I just reinstalled 1.21 to check something. I can see, that it correctly switched to "Charging" at 1:20 tonight, but despite that, it didn't actually charge.
When the Charging Automation kicks in tonight after Midnight I will try and catch the logs. Last night I had gone to bed before 1:20 so I could not observe firsthand.

**Comment by harrymayr** [comment]
> My only (uneducated) guess is, that it is yet again somehow related to the fact that I have a few things permanently plugged into the OffGrid Socket. I guess nobody else is doing that🤷‍♂️

Can you say how much power your devices on the offGrid socket need? I assume that's around 200W as the orange line indicate in your graph above.

**Comment by CommanderROR9** [comment]
![Image](https://github.com/user-attachments/assets/d48709cb-7003-444b-903e-e1644bdc97d4)

> > My only (uneducated) guess is, that it is yet again somehow related to the fact that I have a few things permanently plugged into the OffGrid Socket. I guess nobody else is doing that🤷‍♂️
> 
> Can you say how much power your devices on the offGrid socket need?

Yes..the have a "base load" of around 130W but when the Freezer starts up, it will briefly consume about 700W for less than a Second, then settle around 70W. So... generally 100-200W with occasional spikes.

**Comment by harrymayr** [comment]
OK, than it's more or less the same setup I had a few days before on my SF 800 pro (till the freezer did trigger the overcurrent shutoff permanently). But then I can try to test that and find a solution.

<img width="1278" height="416" alt="Image" src="https://github.com/user-attachments/assets/3db67374-5121-408a-a35a-7372abdec7a1" />

**Comment by CommanderROR9** [comment]
Thanks. I will try to monitor my system when it is supposed to start charging and grab some logs if I can.

**Comment by CommanderROR9** [comment]
Can you explain to me (in layman's terms) what your PR does?

Edit: The reason I am asking is,  because my "charging automation" also takes the Offgid Devices into consideration. So it might create a conflict I have to take into consideration.... ;)

**Comment by harrymayr** [comment]
There are 3 types of manager groups: charge, discharge and idle. The devices will be grouped in at the beginning of the function powerChanged (~ line 407 in manager.py). With this grouping, the limits for the fusegroups will be calculated. All devices which are not recognized as charging or discharging are idle and have an effective input/output-value of 0.
 
To be recognized as a charging device, -d.homeInput.asInt (aka gridInputPower) + d.pwr_offgrid must be < 0
If a device with a load on the offGrid socket is set to 0 (discharge(0) ) it will take all the power for the offGrid socket from the grid so gridInputPower == offGridPower. In this case it is not recognized as a charging device, which is OK.

In general the manager makes a "slow start" by setting a start value of 50W (SmartMode.POWER_START) if a device should charge or discharge. But if you set the inputPower of a device which a load on the offGrid socket to 50W, then gridInputPower == 50 and if  pwr_offGrid == 150, it is not recognized as a charging device, but as idle. In this case the remaing 100W will be taken out off the battery (if not empty).

My PR add the pwr_offgrid to the start value for the device which should started for charging. So it will be recognized as a charging device and the fusegroup limits can be calculated correct.

Hope it is clear now what the problem and the solution is.

**Comment by CommanderROR9** [comment]
I think I might have understood that. I wonder whether it was relevant in my situation though, since the value I send to the 2400AC for the nightly charge is -2400W....🤔
That should be more than enough, even without accounting for the OffGrid consumption?

**Comment by harrymayr** [comment]
The start value of 50W will be set first and if then a device is recognized as charging, it get the power which are demanded (in your case 2400 W)

**Comment by CommanderROR9** [comment]
Ok, now I get it.
My 2400ac did switch to "Charging" according to the logs though...but who knows...

**Comment by CommanderROR9** [comment]
This is interesting....the SF2400AC just started charging as scheduled. And I have no clue why. It didn't work last night, but now it does? Thenknly difference is, that the battery was completely empty today which wasn't the case yesterday 🤔

**Comment by CommanderROR9** [comment]
[latest-2.txt](https://github.com/user-attachments/files/24375358/latest-2.txt)

**Comment by harrymayr** [comment]
I checked the log and yes, the reason ist the empty battery. The gridInputPower is always ~10-20W larger than the offGridPower, if the device take all the power from the grid, so it could be classified as charging device. 

But that what I described above, setting the output to -50W start power, will get 50W from the grid, and 100W out of the battery, if offGrid demand is 150W. In this case, the device couldn't be classified as charging device. But if the battery is empty, it will demand all the power from the grid, even if the output is set to -50W.

**Comment by CommanderROR9** [comment]
Ok, so a fix is still needed. Hopefully the PR will be implemented soon

**Comment by CommanderROR9** [comment]
Just FYI. Here is the Log from today when there was enough Solar and the battery should have charged.

[latest-3.txt](https://github.com/user-attachments/files/24383634/latest-3.txt)

**Comment by CommanderROR9** [comment]
It wasn't fixed in 1.21...but I guess it will be fixed in the next release?
